---
title: "My english activity log"
---

From now on, you will use this article to include every single activity that you do in English in a chronological order (e.g. reading a book in English, watching TV shows and series in English, going to an English Evening in Mons, travelling to an English-speaking country, playing games in English such as the pretty exciting game LyricsTraining, etc.). You can even write a few lines about what you’ve watched/read/done and recommend certain things to your friends. The sky’s the limit! We value personal initiative and we will be happy to read whatever you have to offer.

Permanent : my clash royale and clash of clans games are in english for some years and i watch "clash-a-rama" with subtitles in english and some videos of "orange juice" and "surgical goblin" on youtube.

Before 4 november : I watch some memes in english on instagram and facebook. 

4 november : jour où j'ai crée ce fichier 

7 november : Rick and Morty S1 Ep 1, 2, 3, 4

9 november : Rick and Morty S1 Ep 5,6,7,8,9

10 november : Rick and Morty S1 Ep 10,11, S2 Ep1

11 november : Rick and Morty S2 Ep 2,3,4,5,6
