---
title: "Article 1 : living conditions of pigs in slaughterhouses"
description: |-
  -
author:
  - name: Alessio Anastasia
    url: {}
date: 10-20-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Article analysis n° 1 

### I. Title of the article: 
Pigs: Intelligent Animals Suffering on Farms and in Slaughterhouses  

### II. Name of the Magazine + Source [URL]:
The organisation Peta https://www.peta.org/issues/animals-used-for-food/animals-used-food-factsheets/pigs-intelligent-animals-suffering-factory-farms-slaughterhouses/

### III. Vocabulary

| words from the text | Synonym / explanation in   English | words in french       |
| ------------------- | ---------------------------------- | --------------------- |
| mud                 | clay                               | boue                  |
| crates              | box                                | caisse                |
| nest                | refuge                             | nid                   |
| chunks              | hunk                               | morceaux              |
| hurdle              | hindrance                          | obstacle              |
| sheer               | pure                               |  pur/naturel /intact  |
| scalding            | blazing                            | bouillant             |
| consumption         | uptake/drinking                    | consommation          |
| samples             | pattern                            | échantillons          |
| spread              | dissemination                      | propager              |
| manure              | compost                            | fumier                |
| pits                | trench                             | fosses                |
| dumping             | removal                            | décharger             |
| sprayed             | splash                             | pulvérisé             |
| bonds               | bind (lier)                        | des liens (menotte)   |

### IV. Analysis table

| Researchers                    |   journalist of peta   |
|--------------------------------|------|
| Published in?                  |   7/10/19  |
| General topic?                 |   living conditions of pigs in slaughterhouses and behavior of farmers   |
| Procedure/what   was examined? |   They described how farmers treat pigs. Pigs are in crates everyday 24/24 for their meat and to give born at piglet|
| Conclusions/discovery?         |   They discover the treatment of pigs in slaughterhouses by farmers   |
| Remaining questions?           |     |
















